#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 28 21:42:54 2019

@author: bhavana
"""

""" Do pip install requests """

import requests 

url = "https://www.geeksforgeeks.org/data-structures/"
r = requests.get(url)
print(r.content)